#!/usr/bin/env python3
"""Write `mangools/_spec.py` from the spec itself.

openapi-python-client's templates only see `info.title/description/version`, so
the server URL and the API-key header name never reach the generated package.
Both are contract values that must follow the spec rather than be pasted into
Python, so they are extracted here instead.

Usage:
    python scripts/emit_spec_constants.py openapi.json mangools/_spec.py
"""

from __future__ import annotations

import json
import os
import sys
from typing import Any

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from fetch_spec import sha256_of  # noqa: E402

HEADER = '''"""Constants extracted from the OpenAPI document.

Generated by scripts/emit_spec_constants.py — do not edit.
"""
'''


def api_key_scheme(spec: dict[str, Any]) -> dict[str, Any]:
    schemes = spec.get("components", {}).get("securitySchemes", {})
    candidates = [
        (name, s)
        for name, s in schemes.items()
        if isinstance(s, dict) and s.get("type") == "apiKey" and s.get("in") == "header"
    ]
    if len(candidates) != 1:
        raise SystemExit(f"expected exactly one header apiKey security scheme, found {[n for n, _ in candidates]}")
    return candidates[0][1]


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    src, dst = argv[1], argv[2]

    with open(src, encoding="utf-8") as fh:
        spec = json.load(fh)

    servers = spec.get("servers") or []
    if not servers or not servers[0].get("url"):
        raise SystemExit("spec has no servers[0].url to derive DEFAULT_BASE_URL from")

    scheme = api_key_scheme(spec)
    values = {
        "API_TITLE": spec["info"]["title"],
        "SPEC_VERSION": spec["info"]["version"],
        "SPEC_SHA256": sha256_of(spec),
        "DEFAULT_BASE_URL": servers[0]["url"].rstrip("/"),
        "API_KEY_HEADER": scheme["name"],
    }

    body = "\n".join(f"{k}: str = {json.dumps(v)}" for k, v in values.items())
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write(HEADER + "\n" + body + "\n")

    for k, v in values.items():
        print(f"{k} = {v}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
